name: Login to Docker, build, tag, push and Azure Deploy
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
    
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUBTOKEN }}
        
        - name: Build database image
          run: |
            docker build -t biseras/mongo ./
            
        - name: Build backend image
          run: |
            docker build -t biseras/filmm ./film
            
        - name: Docker database tag
          run: |
            docker tag biseras/mongo biseras/mongo
            
        - name: Docker backend tag
          run: |
            docker tag biseras/filmm biseras/filmm
        
        - name: Docker push database image
          run: |
            docker push biseras/mongo
        
        - name: Docker push backend image
          run: |
            docker push biseras/filmm
            
    deploy:
        needs: build
        runs-on:
            - self-hosted
        steps:
            - uses: actions/checkout@v2
            
            - name: Run scripts
              run: |
                cd ../kii-proekt-film-
                git pull
                cd charts
                helm upgrade --install mongochart mongo
                helm upgrade --install filmchart film
                kubectl rollout restart deployment backend-deployment
